# Generated by Django 2.2.12 on 2020-06-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='expires',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
