version: "3"
services:
  app:
    image: skyride/capritools3:2.1.0
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis

  redis:
    image: redis:5.0
    volumes:
      - redisdata:/data

volumes:
  redisdata:
