# Generated by Django 2.1.7 on 2019-03-30 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0002_mapitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField()),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.System')),
            ],
        ),
    ]
