# Generated by Django 2.2.12 on 2020-06-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0006_auto_20200613_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='fittable_non_singleton',
            field=models.BooleanField(null=True),
        ),
    ]
