# Generated by Django 2.2.12 on 2020-06-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0007_auto_20200613_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
