# Generated by Django 2.2.12 on 2020-06-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0008_auto_20200613_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
