# Generated by Django 2.1.7 on 2019-03-29 23:44

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Localscan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=core.utils.generate_key, max_length=80, unique=True)),
                ('raw', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localscans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalscanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localscan_items', to='core.Alliance')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localscan_items', to='core.Character')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localscan_items', to='core.Corporation')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='localscan.Localscan')),
            ],
        ),
    ]
