# Generated by Django 2.1.7 on 2019-03-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localscan',
            name='accepted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localscan',
            name='rejected',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
