# Generated by Django 2.1.7 on 2019-03-30 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faction'),
        ('localscan', '0002_auto_20190329_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='localscanitem',
            name='faction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localscan_items', to='core.Faction'),
        ),
        migrations.AlterField(
            model_name='localscanitem',
            name='alliance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localscan_items', to='core.Alliance'),
        ),
    ]
