# Generated by Django 2.1.7 on 2019-03-30 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localscan', '0003_auto_20190330_0122'),
        ('sde', '0003_faction')
    ]

    operations = [
        migrations.AlterField(
            model_name='localscanitem',
            name='faction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localscan_items', to='sde.Faction'),
        ),
    ]
