# Generated by Django 2.1.7 on 2019-03-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localscan', '0004_auto_20190330_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localscan',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='localscan',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='localscanitem',
            name='raw',
        ),
    ]
