# Generated by Django 2.1.7 on 2019-03-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localscan', '0005_auto_20190330_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coalition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('colour', models.CharField(max_length=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coalitions', to='localscan.Localscan')),
            ],
        ),
        migrations.AddField(
            model_name='localscanitem',
            name='coalition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='localscan.Coalition'),
        ),
    ]
