# Generated by Django 2.2b1 on 2019-03-09 16:56

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dscan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=core.utils.generate_key, max_length=8, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.System')),
            ],
        ),
        migrations.CreateModel(
            name='DscanObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dscan_objects', to='dscan.Dscan')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dscan_objects', to='sde.Type')),
            ],
        ),
    ]
