# Generated by Django 2.2b1 on 2019-03-09 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dscan',
            name='accepted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dscan',
            name='raw',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dscan',
            name='rejected',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dscanobject',
            name='raw',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dscanobject',
            name='type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='dscan_objects', to='sde.Type'),
        ),
    ]
