# Generated by Django 2.1.7 on 2019-03-29 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dscan', '0004_auto_20190324_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dscan',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dscans', to=settings.AUTH_USER_MODEL),
        ),
    ]
